use std::fs;
use std::path::PathBuf;

use uuid::Uuid;

use serde_json::json;
use synod::adapters::agent::FnAgentAdapter;
use synod::adapters::tool::FnToolAdapter;
use synod::adapters::trace_store::FileTraceStore;
use synod::domain::decision::{DecisionStatus, DecisionType};
use synod::domain::flow_policy::FlowPolicy;
use synod::domain::goal_plan::{GoalPlan, PlannedTask};
use synod::domain::step::{ErrorInfo, Recoverability, StepExecutionResult};
use synod::orchestrator::decision_loop::{DecisionLoop, LoopTerminal};
use synod::registry::agent_registry::AgentRegistry;
use synod::registry::tool_registry::ToolRegistry;

fn temp_workspace(prefix: &str) -> PathBuf {
    let ws = std::env::temp_dir().join(format!("{prefix}-{}", Uuid::new_v4()));
    fs::create_dir_all(&ws).unwrap();
    ws
}

fn sample_task(id: &str, target: &str, hint: DecisionType) -> PlannedTask {
    PlannedTask {
        task_id: id.to_string(),
        description: format!("Process {target}"),
        target: target.to_string(),
        expected_outcome: Some("completed".to_string()),
        decision_type_hint: Some(hint),
    }
}

fn build_loop(workspace: &std::path::Path, max_steps: usize) -> DecisionLoop<FileTraceStore> {
    let mut agents = AgentRegistry::new();
    let analyzer_workspace = workspace.to_path_buf();
    agents
        .register(
            "analyzer",
            FnAgentAdapter::new(move |request| {
                let target =
                    request.input.get("target").and_then(|value| value.as_str()).unwrap_or("");
                match fs::read_to_string(analyzer_workspace.join(target)) {
                    Ok(contents) => {
                        StepExecutionResult::success(json!({"stdout": contents, "target": target}))
                    }
                    Err(error) => StepExecutionResult::failure(
                        ErrorInfo::new("file_read_failed", error.to_string()),
                        Recoverability::ReplanRequired,
                    ),
                }
            }),
        )
        .unwrap();
    let coder_workspace = workspace.to_path_buf();
    agents
        .register(
            "coder",
            FnAgentAdapter::new(move |request| {
                let target =
                    request.input.get("target").and_then(|value| value.as_str()).unwrap_or("");
                let path = coder_workspace.join(target);
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).unwrap();
                }
                let contents = fs::read_to_string(&path).unwrap_or_default();
                let updated = if contents.contains("left - right") {
                    contents.replacen("left - right", "left + right", 1)
                } else if contents.is_empty() {
                    "// generated by contract adapter\n".to_string()
                } else {
                    contents
                };
                fs::write(&path, &updated).unwrap();
                StepExecutionResult::success(
                    json!({"stdout": "changed", "diff": "updated", "changed_files": [target]}),
                )
            }),
        )
        .unwrap();

    let mut tools = ToolRegistry::new();
    tools
        .register(
            "tester",
            FnToolAdapter::new(move |_request| {
                StepExecutionResult::success(json!({"stdout": "tests passed", "exit_code": 0}))
            }),
        )
        .unwrap();
    tools
        .register(
            "replanner",
            FnToolAdapter::new(move |_request| {
                StepExecutionResult::success(json!({"stdout": "replanned"}))
            }),
        )
        .unwrap();
    let trace_store = FileTraceStore::for_workspace(workspace);
    DecisionLoop::new(agents, tools, trace_store, max_steps)
}

#[test]
fn decision_loop_produces_decisions_and_terminates() {
    let workspace = temp_workspace("dl-contract-1");

    // Create a target file so Analyze can read it
    let target_path = workspace.join("src");
    std::fs::create_dir_all(&target_path).unwrap();
    std::fs::write(target_path.join("main.rs"), "fn main() {}").unwrap();

    let plan = GoalPlan::new(
        "Analyze the codebase",
        vec![sample_task("t1", "src/main.rs", DecisionType::Analyze)],
    )
    .unwrap();

    let dl = build_loop(&workspace, 10);
    let (terminal, decisions, trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    assert_eq!(terminal, LoopTerminal::Success);
    assert!(!decisions.is_empty());
    assert!(decisions.iter().all(|d| d.status.is_terminal()));
    assert!(!trace.events.is_empty());
}

#[test]
fn decision_loop_enforces_step_limit_and_returns_exhausted() {
    let workspace = temp_workspace("dl-contract-2");
    let workspace = workspace.as_path();

    // Create multiple tasks that will succeed — but set max_steps to 1
    let target_path = workspace.join("src");
    std::fs::create_dir_all(&target_path).unwrap();
    std::fs::write(target_path.join("a.rs"), "// a").unwrap();
    std::fs::write(target_path.join("b.rs"), "// b").unwrap();

    let plan = GoalPlan::new(
        "Process two files",
        vec![
            sample_task("t1", "src/a.rs", DecisionType::Analyze),
            sample_task("t2", "src/b.rs", DecisionType::Analyze),
        ],
    )
    .unwrap();

    let dl = build_loop(workspace, 1);
    let (terminal, decisions, _trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    assert!(matches!(terminal, LoopTerminal::Exhausted { steps_taken: 1, max_steps: 1 }));
    assert_eq!(decisions.len(), 1);
}

#[test]
fn decision_loop_respects_flow_policy_constraints() {
    let workspace = temp_workspace("dl-contract-3");
    let workspace = workspace.as_path();

    let target_path = workspace.join("src");
    std::fs::create_dir_all(&target_path).unwrap();
    std::fs::write(target_path.join("bug.rs"), "// bug here").unwrap();

    // Task hints Code but bug-fix investigate only allows Analyze
    let plan =
        GoalPlan::new("Fix the bug", vec![sample_task("t1", "src/bug.rs", DecisionType::Code)])
            .unwrap();

    let policy = FlowPolicy::from_builtin("bug-fix").unwrap();
    let dl = build_loop(workspace, 10);
    let (_terminal, decisions, _trace) =
        dl.run(&plan, Some(&policy), &workspace.to_string_lossy(), "sess-1").unwrap();

    // The loop should have overridden Code → Analyze (first allowed type in investigate stage)
    assert!(!decisions.is_empty());
    assert_eq!(decisions[0].decision_type, DecisionType::Analyze);
}

#[test]
fn decision_loop_terminal_state_is_explicit() {
    let workspace = temp_workspace("dl-contract-4");
    let workspace = workspace.as_path();

    let plan =
        GoalPlan::new("Write code", vec![sample_task("t1", "src/lib.rs", DecisionType::Code)])
            .unwrap();

    let dl = build_loop(workspace, 10);
    let (terminal, decisions, _trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    // Code dispatch simulates success, so terminal should be Success
    assert_eq!(terminal, LoopTerminal::Success);
    assert_eq!(decisions.len(), 1);
    assert_eq!(decisions[0].status, DecisionStatus::Verified);
}
