use std::fs;
use std::path::PathBuf;

use uuid::Uuid;

use serde_json::json;
use synod::adapters::agent::FnAgentAdapter;
use synod::adapters::tool::FnToolAdapter;
use synod::adapters::trace_store::FileTraceStore;
use synod::domain::decision::{DecisionStatus, DecisionType, EvidenceRef};
use synod::domain::goal_plan::{GoalPlan, PlannedTask};
use synod::domain::step::{ErrorInfo, Recoverability, StepExecutionResult};
use synod::domain::trace::TraceEventType;
use synod::orchestrator::decision_loop::{DecisionLoop, LoopTerminal, Observation};
use synod::registry::agent_registry::AgentRegistry;
use synod::registry::tool_registry::ToolRegistry;

fn temp_workspace(prefix: &str) -> PathBuf {
    let ws = std::env::temp_dir().join(format!("{prefix}-{}", Uuid::new_v4()));
    fs::create_dir_all(&ws).unwrap();
    ws
}

fn sample_task(id: &str, target: &str, hint: DecisionType) -> PlannedTask {
    PlannedTask {
        task_id: id.to_string(),
        description: format!("Process {target}"),
        target: target.to_string(),
        expected_outcome: Some("completed".to_string()),
        decision_type_hint: Some(hint),
    }
}

fn build_loop(workspace: &std::path::Path, max_steps: usize) -> DecisionLoop<FileTraceStore> {
    let mut agents = AgentRegistry::new();
    let analyzer_workspace = workspace.to_path_buf();
    agents
        .register(
            "analyzer",
            FnAgentAdapter::new(move |request| {
                let target =
                    request.input.get("target").and_then(|value| value.as_str()).unwrap_or("");
                match fs::read_to_string(analyzer_workspace.join(target)) {
                    Ok(contents) => {
                        StepExecutionResult::success(json!({"stdout": contents, "target": target}))
                    }
                    Err(error) => StepExecutionResult::failure(
                        ErrorInfo::new("file_read_failed", error.to_string()),
                        Recoverability::ReplanRequired,
                    ),
                }
            }),
        )
        .unwrap();
    let coder_workspace = workspace.to_path_buf();
    agents
        .register(
            "coder",
            FnAgentAdapter::new(move |request| {
                let target =
                    request.input.get("target").and_then(|value| value.as_str()).unwrap_or("");
                let path = coder_workspace.join(target);
                if let Some(parent) = path.parent() {
                    fs::create_dir_all(parent).unwrap();
                }
                let contents = fs::read_to_string(&path).unwrap_or_default();
                let updated = if contents.contains("left - right") {
                    contents.replacen("left - right", "left + right", 1)
                } else if contents.is_empty() {
                    "// generated by test adapter\n".to_string()
                } else {
                    contents
                };
                fs::write(&path, &updated).unwrap();
                StepExecutionResult::success(
                    json!({"stdout": "changed", "diff": "updated", "changed_files": [target]}),
                )
            }),
        )
        .unwrap();

    let mut tools = ToolRegistry::new();
    tools
        .register(
            "tester",
            FnToolAdapter::new(move |_request| {
                StepExecutionResult::success(json!({"stdout": "tests passed", "exit_code": 0}))
            }),
        )
        .unwrap();
    tools
        .register(
            "replanner",
            FnToolAdapter::new(move |_request| {
                StepExecutionResult::success(json!({"stdout": "replanned"}))
            }),
        )
        .unwrap();
    let trace_store = FileTraceStore::for_workspace(workspace);
    DecisionLoop::new(agents, tools, trace_store, max_steps)
}

#[test]
fn observe_phase_collects_workspace_files_and_evidence() {
    // Observation struct captures workspace state correctly
    let obs = Observation {
        workspace_files: vec!["src/main.rs".to_string()],
        last_decision: None,
        accumulated_evidence: vec![EvidenceRef::file("src/lib.rs")],
        remaining_tasks: vec!["src/main.rs".to_string()],
    };
    assert_eq!(obs.workspace_files.len(), 1);
    assert!(obs.last_decision.is_none());
    assert_eq!(obs.accumulated_evidence.len(), 1);
}

#[test]
fn decide_phase_selects_action_from_plan_task() {
    let workspace = temp_workspace("dl-decide");
    let workspace = workspace.as_path();

    std::fs::create_dir_all(workspace.join("src")).unwrap();
    std::fs::write(workspace.join("src/target.rs"), "// code").unwrap();

    let plan = GoalPlan::new(
        "Analyze target",
        vec![sample_task("t1", "src/target.rs", DecisionType::Analyze)],
    )
    .unwrap();

    let dl = build_loop(workspace, 10);
    let (_terminal, decisions, _trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    assert_eq!(decisions[0].decision_type, DecisionType::Analyze);
    assert_eq!(decisions[0].target, "src/target.rs");
}

#[test]
fn verify_phase_transitions_decision_status() {
    let workspace = temp_workspace("dl-verify");
    let workspace = workspace.as_path();

    std::fs::create_dir_all(workspace.join("src")).unwrap();
    std::fs::write(workspace.join("src/f.rs"), "fn f() {}").unwrap();

    let plan =
        GoalPlan::new("Read file", vec![sample_task("t1", "src/f.rs", DecisionType::Analyze)])
            .unwrap();

    let dl = build_loop(workspace, 10);
    let (_terminal, decisions, _trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    // Analyze on existing file → success → Verified
    assert_eq!(decisions[0].status, DecisionStatus::Verified);
    assert!(decisions[0].tool_result.is_some());
    assert!(decisions[0].tool_result.as_ref().unwrap().success);
}

#[test]
fn exhaustion_terminal_when_max_steps_reached() {
    let workspace = temp_workspace("dl-exhaust");
    let workspace = workspace.as_path();

    std::fs::create_dir_all(workspace.join("src")).unwrap();
    std::fs::write(workspace.join("src/a.rs"), "a").unwrap();
    std::fs::write(workspace.join("src/b.rs"), "b").unwrap();
    std::fs::write(workspace.join("src/c.rs"), "c").unwrap();

    let plan = GoalPlan::new(
        "Process three files",
        vec![
            sample_task("t1", "src/a.rs", DecisionType::Analyze),
            sample_task("t2", "src/b.rs", DecisionType::Analyze),
            sample_task("t3", "src/c.rs", DecisionType::Analyze),
        ],
    )
    .unwrap();

    let dl = build_loop(workspace, 2);
    let (terminal, decisions, _trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    assert!(matches!(terminal, LoopTerminal::Exhausted { steps_taken: 2, max_steps: 2 }));
    assert_eq!(decisions.len(), 2);
}

#[test]
fn trace_contains_decision_events() {
    let workspace = temp_workspace("dl-trace");
    let workspace = workspace.as_path();

    std::fs::create_dir_all(workspace.join("src")).unwrap();
    std::fs::write(workspace.join("src/t.rs"), "test").unwrap();

    let plan = GoalPlan::new("Analyze", vec![sample_task("t1", "src/t.rs", DecisionType::Analyze)])
        .unwrap();

    let dl = build_loop(workspace, 10);
    let (_terminal, _decisions, trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();

    let event_types: Vec<_> = trace.events.iter().map(|e| e.event_type).collect();
    assert!(event_types.contains(&TraceEventType::GoalPlanCreated));
    assert!(event_types.contains(&TraceEventType::DecisionCreated));
    assert!(event_types.contains(&TraceEventType::DecisionDispatched));
    assert!(event_types.contains(&TraceEventType::DecisionVerified));
    assert!(event_types.contains(&TraceEventType::TerminalRecorded));
}

#[test]
fn recovery_from_failed_analysis_marks_recovered() {
    let workspace = temp_workspace("dl-recover");
    let workspace = workspace.as_path();

    // Target file does NOT exist → Analyze will fail
    let plan = GoalPlan::new(
        "Analyze missing file",
        vec![sample_task("t1", "src/nonexistent.rs", DecisionType::Analyze)],
    )
    .unwrap();

    let dl = build_loop(workspace, 5);
    let (terminal, _decisions, trace) =
        dl.run(&plan, None, &workspace.to_string_lossy(), "sess-1").unwrap();
    let has_failed = trace.events.iter().any(|e| e.event_type == TraceEventType::DecisionFailed);
    let has_recovered =
        trace.events.iter().any(|e| e.event_type == TraceEventType::DecisionRecovered);
    assert!(has_failed);
    assert!(has_recovered);

    // Terminal should be Exhausted since recovery doesn't complete the task
    assert!(matches!(terminal, LoopTerminal::Exhausted { .. }));
}
